services:
  inventory_service:
    image: postgres
    container_name: inventory
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
    - items:/var/lib/postgresql/data

volumes:
  items: