spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: inventory
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
  endpoint:
    loggers:
      enabled: true

logging:
  level:
    web: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate: DEBUG
